"""db_criar_cadastro

Revision ID: e2f60347f01e
Revises: 51e3774f0a2c
Create Date: 2023-08-17 09:30:19.339406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f60347f01e'
down_revision = '51e3774f0a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_model', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(length=14), nullable=False))

    # ### end Alembic commands ###
